### PR TITLE
reject()

### PR DESCRIPTION
**Pull request by plu**
Hi,

I've implemented the reject() method which is supported from RabbitMQ 2.0.0 as well as some minor things. Would be nice if you could review my changes :).

Cheers,
plu

### CODE REVIEW

**Comment by cooldaemon** [comment]
Thank you for your very nice patches.

I tried to run the following commands.

> git remote add -f plu http://github.com/plu/RabbitFoot.git
> git merge plu/master

But failed it because your repository is private mode.
Would you please teach me how to merge it.

**Comment by plu** [comment]
Hey,

I've pushed that repository to my former companies github account: xing
You can add the remote doing this:

git remote add plu http://github.com/xing/RabbitFoot.git

Cheers,
plu

**Comment by cooldaemon** [comment]
Thank you for your advice.
I merged your patches.

Thanks,

**Comment by plu** [comment]
Great, thank you very much! cooldaemon++ :)

**Pull request merged**
